# Generated by Django 5.2.5 on 2025-08-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0002_table_employee_delete_workplace"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="user",
        ),
        migrations.RemoveField(
            model_name="table",
            name="max_seats",
        ),
        migrations.AddField(
            model_name="employee",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="role",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="table",
            name="number",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
