# Generated by Django 5.2.5 on 2025-08-22 21:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Фронтенд, Бэкенд, Тестирование', max_length=100, verbose_name='Название навыка')),
                ('category', models.CharField(blank=True, help_text='Категория навыка (технический, управленческий и т.д.)', max_length=100, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание навыка')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский'), ('O', 'Другой'), ('N', 'Не указано')], default='N', max_length=1, verbose_name='Пол')),
                ('middle_name', models.CharField(blank=True, help_text='При наличии', max_length=150, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(blank=True, help_text='Формат: ГГГГ-ММ-ДД', null=True, verbose_name='Дата рождения')),
                ('phone_number', models.CharField(blank=True, help_text='Контактный телефон', max_length=20, verbose_name='Телефон')),
                ('hire_date', models.DateField(blank=True, help_text='Когда сотрудник был принят на работу', null=True, verbose_name='Дата приема на работу')),
                ('position', models.CharField(blank=True, help_text='Текущая должность сотрудника', max_length=200, verbose_name='Должность')),
                ('department', models.CharField(blank=True, help_text='Отдел или подразделение', max_length=200, verbose_name='Отдел')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Подробное описание сотрудника, опыт работы, достижения', verbose_name='Описание')),
                ('is_active_employee', models.BooleanField(default=True, help_text='Отметьте, если сотрудник работает в компании', verbose_name='Активный сотрудник')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(help_text='Оценка от 1 (начальный) до 10 (эксперт)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Уровень навыка (1-10)')),
                ('experience_years', models.DecimalField(decimal_places=1, default=0, help_text='Количество лет опыта с этим навыком', max_digits=3, verbose_name='Опыт (лет)')),
                ('last_used', models.DateField(blank=True, help_text='Когда в последний раз использовался этот навык', null=True, verbose_name='Последнее использование')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_skills', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Навык сотрудника',
                'verbose_name_plural': 'Навыки сотрудников',
                'ordering': ['-level', 'skill__name'],
                'unique_together': {('employee', 'skill')},
            },
        ),
    ]
