# Generated by Django 5.2.5 on 2025-08-23 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="employeeskill",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="address",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="middle_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="employeeimage",
            name="description",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="description",
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("developer", "Developer"),
                    ("tester", "Tester"),
                    ("manager", "Manager"),
                ],
                default="developer",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employeeimage",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="employeeskill",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name="employeeskill",
            name="level",
        ),
    ]
