# Generated by Django 5.2.5 on 2025-08-23 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employeeskill_level_alter_skill_name_employee_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="position",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="salary",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="user",
        ),
        migrations.AddField(
            model_name="employee",
            name="experience",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="first_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="last_name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="employee_photos/"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="skills",
            field=models.ManyToManyField(
                through="employees.EmployeeSkill", to="employees.skill"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("visitor", "Посетитель"),
                    ("watcher", "Смотритель"),
                    ("admin", "Администратор"),
                ],
                default="visitor",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Workplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employees.employee",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="EmployeeImage",
        ),
    ]
